name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t tima-portfolio .
          docker tag tima-portfolio ${{ secrets.DOCKER_USERNAME }}/tima-portfolio
          docker push ${{ secrets.DOCKER_USERNAME }}/tima-portfolio

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/tima-portfolio
            docker stop tima-portfolio || true
            docker rm tima-portfolio || true
            docker run -d --name tima-portfolio -p 3039:3000 ${{ secrets.DOCKER_USERNAME }}/tima-portfolio